name: Fetch TV Shows Weekly

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python fetch_tv_shows.py

      - name: Commit and push updated JSON
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}  # Uses your Personal Access Token
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull origin main  # Ensures the repo is up to date
          git add tv_shows_sonarr.json
          git commit -m "Update TV shows list" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git main
